python load_movoto_data.py /Applications/MAMP/htdocs/realdata/1/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log1.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/2/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log2.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/3/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log3.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/4/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log4.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/5/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log5.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/6/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log6.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/7/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log7.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/8/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log8.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/9/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log9.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/10/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log10.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/11/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log11.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/12/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log12.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/13/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log13.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/14/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log14.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/15/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log15.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/16/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log16.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/17/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log17.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/18/sample_bay_area.json  ~/Downloads/sunnyvale_cupertino.csv > /tmp/log18.txt
