python load_movoto_data.py /Applications/MAMP/htdocs/realdata/2/sample_bay_area.json > log2.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/3/sample_bay_area.json > log3.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/4/sample_bay_area.json > log4.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/5/sample_bay_area.json > log5.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/6/sample_bay_area.json > log6.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/7/sample_bay_area.json > log7.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/8/sample_bay_area.json > log8.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/9/sample_bay_area.json > log9.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/10/sample_bay_area.json > log10.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/11/sample_bay_area.json > log11.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/12/sample_bay_area.json > log12.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/13/sample_bay_area.json > log13.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/14/sample_bay_area.json > log14.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/15/sample_bay_area.json > log15.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/16/sample_bay_area.json > log16.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/17/sample_bay_area.json > log17.txt
python load_movoto_data.py /Applications/MAMP/htdocs/realdata/18/sample_bay_area.json > log18.txt
